name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Vars
      id: vars
      run: |
        echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
  
    - name: Build image
      run: |
        docker build . --file Dockerfile \
          --tag ghcr.io/sampozki/botto:latest \
          --tag ghcr.io/sampozki/botto:${SHORT_SHA}
        docker images

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Push the image to ghcr
      run: |
        docker push ghcr.io/sampozki/botto:latest
        docker push ghcr.io/sampozki/botto:${SHORT_SHA}